name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *'  # Ejecutar cada hora
  workflow_dispatch:  # Permite ejecutar manualmente cuando quieras

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync latest upstream changes
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/gpsyrou/tube-virality.git
          git remote -v

      - name: Fetch upstream
        run: |
          git fetch upstream
          git log --oneline --graph --decorate --all -n 10

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Merge upstream
        run: |
          git merge upstream/main --no-edit
          git push origin main
