name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *'  # Ejecutar cada hora
  workflow_dispatch:  # Permite ejecutar manualmente cuando quieras

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Sync fork with upstream repository
        uses: TG908/fork-sync@v1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: gpsyrou
          base: main
          head: main
          repo: tube-virality
